// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PolicyBased.Infra.Models
{
    public partial class Application
    {
        public Application()
        {
            Permissions = new HashSet<Permission>();
            Policies = new HashSet<Policy>();
            Roles = new HashSet<Role>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}