// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PolicyBased.Infra.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PolicyBased.Infra.Persistence.Context
{
    public partial interface IPolicyTestDBContextProcedures
    {
        Task<List<GetUserPermissionsResult>> GetUserPermissionsAsync(string UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
