// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PolicyBased.Infra.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PolicyBased.Infra.Persistence.Context
{
    public partial class PolicyTestDBContext
    {
        private IPolicyTestDBContextProcedures _procedures;

        public virtual IPolicyTestDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new PolicyTestDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPolicyTestDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetUserPermissionsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class PolicyTestDBContextProcedures : IPolicyTestDBContextProcedures
    {
        private readonly PolicyTestDBContext _context;

        public PolicyTestDBContextProcedures(PolicyTestDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetUserPermissionsResult>> GetUserPermissionsAsync(string UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Size = 512,
                    Value = UserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetUserPermissionsResult>("EXEC @returnValue = [pbac].[GetUserPermissions] @UserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
